### ISSUE TITLE
Unable to create database, got error: decode response: unexpected Content-Type: text/plain

### ISSUE THREAD

**Issue by ricardogomes** [jpedroh/terraform-provider-turso#17]
I'm getting this error with the following elements:

**Unable to create database, got error: decode response: unexpected Content-Type: text/plain**

```terraform
terraform {
  required_providers {
     turso = {
      source = "jpedroh/turso"
      version = "0.2.0"
    }
  }
}

provider "turso" {
  api_token = "<TOKEN>"
}
```

```terraform
resource "turso_database" "testing" {
  organization_name = "<MY_ORG>"
  group             = "default"
  name              = "testing"
}
```

The <> are replaced with actual values

**Comment by ainsleyclark** [comment]
Same here

`Unable to create database, got error: decode response: unexpected Content-Type: text/plain`

@jpedroh any ideas?

**Comment by jpedroh** [comment]
Hello!

Sorry for taking so long to answer this, been busy with a few side things.

I've analyzed it a little and somehow, the API for Turso started randomly returning Content Type text-plain for valid JSON. This then breaks the behaviour of the autogenerated swagger client. I'm thinking in opening a PR for forcing the response content type to be application/json so the api response parse do not fail

**Comment by jpedroh** [comment]
Ok I've updated the swagger definitions and gave it a try and it seems to be working. Can you guys give a try? I've published a new version 0.2.1.

**Comment by jsolly** [comment]
Hmmm. To resurrect this issue, I am running into this exact issue with 0.2.1

The apply worked once and the db got created, but after a re-apply things started going sideways. I think the problem is that the database is deleted, but tf thinks the db token still exists
```
Planning failed. Terraform encountered an error while generating this plan.

╷
│ Error: Client Error
│ 
│   with module.backend.module.metadata-sql.turso_database.database,
│   on backend/metadata/SQL/main.tf line 14, in resource "turso_database" "database":
│   14: resource "turso_database" "database" {
│ 
│ Unable to read database, got error: decode response: unexpected Content-Type: text/plain
╵
```

```

Terraform used the selected providers to generate the following execution plan. Resource actions are indicated with the
following symbols:
  - destroy

Terraform planned the following actions, but then encountered a problem:

  # module.backend.module.metadata-sql.turso_database_token.app_token will be destroyed
  # (because turso_database_token.app_token is not in configuration)
  - resource "turso_database_token" "app_token" {
      - authorization     = "full-access" -> null
      - database_name     = "DB_NAME" -> null
      - expiration        = "never" -> null
      - jwt               = (sensitive value) -> null
      - organization_name = "NAME" -> null
    }

Plan: 0 to add, 0 to change, 1 to destroy.
╷
│ Error: Client Error
│ 
│ Unable to read database, got error: decode response: unexpected Content-Type: text/plain
╵
```

**Comment by jsolly** [comment]
Update. I commented out all the Turso resources and ran these commands:

```
# Remove the token first
terraform state rm module.backend.module.metadata-sql.turso_database_token.app_token

# Remove the database
terraform state rm module.backend.module.metadata-sql.turso_database.database
```

Then I uncommented the resources and tried a `terraform apply` again. That created everything successfully.

But then I immediately tried another terraform apply (expecting no changes) and got this error instead
```
Planning failed. Terraform encountered an error while generating this plan.

╷
│ Error: Client Error
│ 
│   with module.backend.module.metadata-sql.turso_database.database,
│   on backend/metadata/SQL/main.tf line 14, in resource "turso_database" "database":
│   14: resource "turso_database" "database" {
│ 
│ Unable to read database, got error: decode response: decode application/json: decode GetDatabaseOK: callback: decode field
│ "database": decode Database: callback: decode field "schema": unexpected byte 110 'n' at 410
```

**Comment by jpedroh** [comment]
If anyone is still interested in this issue, I've published a new version 0.2.2 that seems to fix the issue whent the `schema` field is null on the database. Feedback and new reports are pretty much appreciated.
